#!/bin/bash

# Get branch name from command line parameter
branch_name=$1

# Append current date to branch name
branch_name="$branch_name-$(date +'%d-%m-%Y_%H%M_%Z')"

# Checkout master branch
git checkout master

# Create new branch based on master
git checkout -b $branch_name

